export const actions = {
    ADD_PLAYER: "ADD_PLAYER",
    REMOVE_PLAYER: "REMOVE_PLAYER",
    ADD_POINTS: "ADD_POINTS",
    UPDATE_MAX_POINTS: "UPDATE_MAX_POINTS",
    UPDATE_CARDS_PER_ROW: "UPDATE_CARDS_PER_ROW",
};