export const actions = {
    ADD_PLAYER: "ADD_PLAYER",
    REMOVE_PLAYER: "REMOVE_PLAYER",
    ADD_POINTS: "ADD_POINTS",
    UPDATE_SETTINGS: "UPDATE_SETTINGS",
    CLEAR_POINTS: "CLEAR_POINTS",
    CLEAR_DATA: "CLEAR_DATA"
};